var testData = {
  dateLogs:[
    {
      dateId:"05-30-2020",
      eventFlag:true,
      eventTitle:"Road Trip",
      eventDescription:"We've grabbed our friends and we're going on an adventure.",
      priorityFlag:false,
      noticeFlag:true,
      noticeDetails:"We meet at the gas station at 6am and leave at 6:30!",
      attReqFlag:false,
      attReqValue:undefined,
      availFlag:false,
      availValue:undefined,
      availDetails:"",
      unavailFlag:false,
      unavailValue:undefined,
      unavailDetails:"",
      timelineFlag:false,
      timelineDetails:"",
    },
    {
      dateId:"05-26-2020",
      eventFlag:false,
      eventTitle:"Road Trip",
      eventDescription:"We've grabbed our friends and we're going on an adventure.",
      priorityFlag:false,
      noticeFlag:true,
      noticeDetails:"Make sure to start packing for the road trip now!",
      attReqFlag:false,
      attReqValue:undefined,
      availFlag:false,
      availValue:undefined,
      availDetails:"",
      unavailFlag:false,
      unavailValue:undefined,
      unavailDetails:"",
      timelineFlag:false,
      timelineDetails:"",
    },
    {
      dateId:"05-25-2020",
      eventFlag:true,
      eventTitle:"Meeting",
      eventDescription:"We gotta plan our moves going forward.",
      priorityFlag:true,
      noticeFlag:false,
      noticeDetails:"",
      attReqFlag:true,
      attReqValue:10,
      availFlag:true,
      availValue:11,
      availDetails:"",
      unavailFlag:true,
      unavailValue:3,
      unavailDetails:"",
      timelineFlag:true,
      timelineDetails:"Meeting went well enough. A lot was discussed and progress was made.",
    },
    {
      dateId:"05-15-2020",
      eventFlag:true,
      eventTitle:"BBQ",
      eventDescription:"Just hangin' out and grilling.",
      priorityFlag:false,
      noticeFlag:false,
      noticeDetails:"",
      attReqFlag:false,
      attReqValue:undefined,
      availFlag:false,
      availValue:undefined,
      availDetails:"",
      unavailFlag:false,
      unavailValue:undefined,
      unavailDetails:"",
      timelineFlag:true,
      timelineDetails:"It was fun! A lot of people we able to make it and the hot dogs were delicious!",
    },
  ]
};

//OPTIONAL CODE TO ADD TEST DATA
/*if(logs.findOne() == undefined){
  logs.insert({
    dateId:"05-30-2020",
    sortId:"2020-05-30",
    year:2020,
    month:05,
    day:30,
    eventFlag:true,
    eventTitle:"Road Trip",
    eventDescription:"We've grabbed our friends and we're going on an adventure.",
    priorityFlag:false,
    noticeFlag:true,
    noticeDetails:"We meet at the gas station at 6am and leave at 6:30!",
    attReqFlag:false,
    attReqValue:undefined,
    availFlag:false,
    availValue:undefined,
    availDetails:"",
    unavailFlag:false,
    unavailValue:undefined,
    unavailDetails:"",
    timelineFlag:false,
    timelineDetails:"",
  });
  logs.insert({
    dateId:"05-26-2020",
    sortId:"2020-05-26",
    year:2020,
    month:05,
    day:26,
    eventFlag:false,
    eventTitle:"Road Trip",
    eventDescription:"We've grabbed our friends and we're going on an adventure.",
    priorityFlag:false,
    noticeFlag:true,
    noticeDetails:"Make sure to start packing for the road trip now!",
    attReqFlag:false,
    attReqValue:undefined,
    availFlag:false,
    availValue:undefined,
    availDetails:"",
    unavailFlag:false,
    unavailValue:undefined,
    unavailDetails:"",
    timelineFlag:false,
    timelineDetails:"",
  });
  logs.insert({
    dateId:"05-25-2020",
    sortId:"2020-05-25",
    year:2020,
    month:05,
    day:25,
    eventFlag:true,
    eventTitle:"Meeting",
    eventDescription:"We gotta plan our moves going forward.",
    priorityFlag:true,
    noticeFlag:false,
    noticeDetails:"",
    attReqFlag:true,
    attReqValue:10,
    availFlag:true,
    availValue:11,
    availDetails:"",
    unavailFlag:true,
    unavailValue:3,
    unavailDetails:"",
    timelineFlag:true,
    timelineDetails:"Meeting went well enough. A lot was discussed and progress was made.",
  });
  logs.insert({
    dateId:"05-15-2020",
    sortId:"2020-05-15",
    year:2020,
    month:05,
    day:15,
    eventFlag:true,
    eventTitle:"BBQ",
    eventDescription:"Just hangin' out and grilling.",
    priorityFlag:false,
    noticeFlag:false,
    noticeDetails:"",
    attReqFlag:false,
    attReqValue:undefined,
    availFlag:false,
    availValue:undefined,
    availDetails:"",
    unavailFlag:false,
    unavailValue:undefined,
    unavailDetails:"",
    timelineFlag:true,
    timelineDetails:"It was fun! A lot of people we able to make it and the hot dogs were delicious!",
  });
};*/